config/routes.rb
Rails.application.routes.draw do
  root to: 'heroes#index'
  devise_for :users, controllers: {sessions: 'sessions'}
  %w( 401 404 422 500 ).each do |code|
    get code, to: 'errors#show', code: code
  end

  get 'about', to: 'about#index'
  get 'about/contact'

  resources :heroes, only: [:index, :show]
  resources :accounts, only: [:index, :show] do
    member do
      get 'goals'
      get 'materials'
    end
  end
  resources :account_heroes, only: [:edit, :create, :update, :destroy]

  # these routes are JSON-only:
  get 'account_heroes', to: 'account_heroes#index', constraints: lambda {|request| request.format.json? }
  get 'account_heroes/:id', to: 'account_heroes#show', constraints: lambda {|request| request.format.json? }
end

app/views/shared/_dom_settings.html.erb
<div>
  <span id="top-uri" style="display: none;"><%= request.protocol + request.host_with_port %></span>
</div>

app/views/shared/_flash.html.erb
<% if notice.present? %>
  <aside class="alert alert-info">
    <%= notice %>
  </aside>
<% end %>
<% if alert.present? %>
  <aside class="alert alert-danger">
    <%= alert %>
  </aside>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-default">
    <div class="container">
      <p class="navbar-text">Idle Herder app &copy; 2017 Brent J. Nordquist&nbsp;&nbsp;Some Rights Reserved.</p>
      <p class="navbar-text"><%= link_to 'Not affiliated with Idle Heroes', about_path(anchor: 'disclaimer') %></p>
    </div>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#ih-navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Idle Herder', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="ih-navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= active_class('heroes') %>">
            <%= link_to 'Heroes', heroes_path %>
          </li>
          <% if user_signed_in? %>
            <li class="<%= active_class('accounts') %>">
              <%= link_to 'My Heroes', account_path(current_account) %>
            </li>
            <li class="<%= active_class('materials') %>">
              <%= link_to 'My Materials', materials_account_path(current_account) %>
            </li>
            <li class="<%= active_class('goals') %>">
              <%= link_to 'My Goals', goals_account_path(current_account) %>
            </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? && (controller_path !~ %r{^devise/}) %>
            <li>
              <%= link_to 'Sign In', new_user_session_path, method: 'get' %>
            </li>
          <% end %>
          <% if user_signed_in? && (controller_path != 'devise/registrations') %>
            <li>
              <%= link_to 'Edit User', edit_user_registration_path, method: 'get' %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' %>
            </li>
          <% end %>
          <li class="<%= active_class('about') %>">
            <%= link_to 'About', about_path %>
          </li>
          <li class="<%= active_class('contact') %>">
            <%= link_to 'Contact', about_contact_path %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_meta_tags.html.erb
<% [:description, :heroname, :stars, :faction, :role].each do |tag| %>
  <% if content_for?(:"meta_#{tag}") %>
    <meta name="<%= tag %>" content="<%= content_for(:"meta_#{tag}") %>" />
  <% end %>
<% end %>